# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'compile'

- task: CmdLine@2
  inputs:
    script: |
      - task: CmdLine@2
        inputs:
          script: 'powershell "[Net.ServicePointManager]::SecurityProtocol = ''tls12''; irm https://detect.synopsys.com/detect7.ps1?$(Get-Random) | iex;" detect --blackduck.url=https://partner-demo.blackduck.synopsys.com --blackduck.api.token=YjUwNzcwMDAtNWM3Zi00ZjBjLThkZjEtNTlkZTMwNDhhMzA1OjU4MmVlMmYwLTc5ZmQtNGIxNi05MTAyLTNiZWRkMmMxMGUwZg==   --detect.impact.analysis.enabled=true --detect.policy.check.fail.on.severities=ALL  --detect.blackduck.scan.mode=RAPID --detect.impact.analysis.output.path=c:\codebases1\helo-java-script'