Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile '
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

 - task: SynopsysDetectTask@7
   inputs:
     BlackDuckService: 'Partner-Demo'
     DetectArguments: '--detect.policy.check.fail.on.severities=ALL  --detect.blackduck.scan.mode=RAPID --detect.impact.analysis.output.path=c:\codebases1\helo-java-script'
     DetectVersion: 'latest'