 Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile -DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CmdLine@2
  inputs:
    script: 'powershell "[Net.ServicePointManager]::SecurityProtocol = ''tls12''; irm https://detect.synopsys.com/detect7.ps1?$(Get-Random) | iex;" detect --blackduck.url=https://partner-demo.blackduck.synopsys.com --blackduck.api.token=YjUwNzcwMDAtNWM3Zi00ZjBjLThkZjEtNTlkZTMwNDhhMzA1OjU4MmVlMmYwLTc5ZmQtNGIxNi05MTAyLTNiZWRkMmMxMGUwZg==   --detect.impact.analysis.enabled=true --detect.policy.check.fail.on.severities=ALL  --detect.blackduck.scan.mode=RAPID --detect.impact.analysis.output.path=c:\codebases1\helo-java-script'
  