# example ADO pipeline for Polaris using the Bridge CLI good test
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: group
- name: BRIDGE_POLARIS_APPLICATION_NAME
  value: 'AJWhello-java'      #change this name
- name: BRIDGE_POLARIS_PROJECT_NAME
  value: 'AJWHelloJ'    # change this name
steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'blackduck'
    bridge_blackduck_url: 'https://poc304.blackduck.synopsys.com'
    bridge_blackduck_token: 'xxxxxxxxxxxmFAKE_TOKENLWE1NzctNWMwNTYxMDMxN2ZkOjczMzkzZjQ5LWZkZWQtNGEzNC04ZjA3LTVmMzllNmI4MDg1Mw'
    bridge_blackduck_scan_full: true
- bash: |
    curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $(Agent.TempDirectory) bridge.zip && rm -f bridge.zip
    $(Agent.TempDirectory)/synopsys-bridge --stage polaris polaris.assessment.types=SAST
  displayName: 'Polaris Scan'
  env:
    BRIDGE_POLARIS_ACCESSTOKEN: $(BRIDGE_POLARIS_ACCESSTOKEN)
    BRIDGE_POLARIS_SERVERURL: $(BRIDGE_POLARIS_SERVERURL)
    

- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: true
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: true
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
