name: Coverity Self-hosted Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #workflow_dispatch:

jobs:
  coverity_self_hosted_runner_steps:
    runs-on: self-hosted

    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVBIN: /home/mhnam/sig/coverity/analysis/current/bin
      COVERITY_PROJECT: hello-java-coverity-demo
      BLDCMD: mvn -B clean package -DskipTests
      CHECKERS: --webapp-security
      IDIR: idir      

    steps:
    - uses: AutoModality/action-clean@v1    
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        export PATH=$PATH:$COVBIN
        set -x
        rm -rf $IDIR
        $COVBIN/cov-configure --java
        $COVBIN/cov-build --dir $IDIR --fs-capture-search $GITHUB_WORKSPACE $BLDCMD
        $COVBIN/cov-analyze --dir $IDIR --ticker-mode none --strip-path $GITHUB_WORKSPACE $CHECKERS
        $COVBIN/cov-commit-defects --dir $IDIR --ticker-mode none --url $COV_URL --user $COV_USER --password $COVERITY_PASSPHRASE  --stream $COVERITY_PROJECT-${GITHUB_REF##*/} --scm git \
          --description $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID --target $RUNNER_OS --version $GITHUB_SHA

    - name: Coverity Quality Gate
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/api/viewContents/issues/v1/High%20Impact%20Outstanding?projectId=$COVERITY_PROJECT > results.json
        if [ $(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat results.json | jq .viewContentsV1.rows; exit 1; fi

    - id: changeset
      name: Get Pull Request Changeset
      uses: jitterbit/get-changed-files@v1
      if: ${{ github.event_name == 'pull_request' }}

    - name: Coverity Incremental Scan
      if: ${{ github.event_name == 'pull_request' && steps.changeset.outputs.added_modified != '' }}
      run: |
        export PATH=$PATH:$COVBIN
        set -x
        $COVBIN/cov-run-desktop --dir $IDIR --url $COV_URL --user $COV_USER --password $COVERITY_PASSPHRASE --stream $COVERITY_PROJECT-$GITHUB_BASE_REF --build $BLDCMD
        $COVBIN/cov-run-desktop --dir $IDIR --url $COV_URL --user $COV_USER --password $COVERITY_PASSPHRASE --stream $COVERITY_PROJECT-$GITHUB_BASE_REF --present-in-reference false \
          --ignore-uncapturable-inputs true --exit1-if-defects true ${{ steps.changeset.outputs.added_modified }}
